### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Paren7** [let-def/texpresso#42]
make -C src texpresso
make[1]: 进入目录“/home/paren/texpresso/src”
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/driver.o -Idvi/ driver.c
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/main.o -Idvi/ main.c
main.c: In function ‘find_diff’:
main.c:514:27: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘const struct fz_buffer_s’}
  514 |   int i, len = fz_mini(buf->len, size);
      |                           ^~
main.c: In function ‘realize_change’:
main.c:558:19: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  558 |     uint8_t *p = b->data;
      |                   ^~
make[1]: *** [Makefile:34：../build/objects/main.o] 错误 1
make[1]: 离开目录“/home/paren/texpresso/src”

libmupdf-dev 已经是最新版 (1.16.1+ds1-1ubuntu1)。
libsdl2-dev 已经是最新版 (2.0.10+dfsg1-3)。

**Comment by let-def** [comment]
The simplest fix is to use a recent versions of mupdf (fz_buffer implementation has been public since 1.17).
Otherwise, can you run `make -k` and share the output to see if there are other errors?

**Comment by Paren7** [comment]
I execute make -k, the error as follows 

> make -C src texpresso
make[1]: 进入目录“/home/paren/texpresso/src”
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/main.o -Idvi/ main.c
main.c: In function ‘find_diff’:
main.c:514:27: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘const struct fz_buffer_s’}
  514 |   int i, len = fz_mini(buf->len, size);
      |                           ^~
main.c: In function ‘realize_change’:
main.c:558:19: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  558 |     uint8_t *p = b->data;
      |                   ^~
make[1]: *** [Makefile:34：../build/objects/main.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/state.o -Idvi/ state.c
state.c: In function ‘pop_value’:
state.c:81:10: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
   81 |   if (buf->len < len) abort();
      |          ^~
make[1]: *** [Makefile:34：../build/objects/state.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/fs.o -Idvi/ fs.c
fs.c: In function ‘filesystem_new’:
fs.c:75:13: warning: implicit declaration of function ‘fz_malloc_struct_array’; did you mean ‘fz_malloc_struct’? [-Wimplicit-function-declaration]
   75 |     table = fz_malloc_struct_array(ctx, 64, tablecell);
      |             ^~~~~~~~~~~~~~~~~~~~~~
      |             fz_malloc_struct
fs.c:75:45: error: expected expression before ‘tablecell’
   75 |     table = fz_malloc_struct_array(ctx, 64, tablecell);
      |                                             ^~~~~~~~~
fs.c: In function ‘table_resize’:
fs.c:129:59: error: expected expression before ‘tablecell’
  129 |   tablecell *newtab = fz_malloc_struct_array(ctx, newcap, tablecell);
      |                                                           ^~~~~~~~~
make[1]: *** [Makefile:34：../build/objects/fs.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/incdvi.o -Idvi/ incdvi.c
incdvi.c: In function ‘add_page’:
incdvi.c:48:18: warning: implicit declaration of function ‘fz_malloc_struct_array’; did you mean ‘fz_malloc_struct’? [-Wimplicit-function-declaration]
   48 |       d->pages = fz_malloc_struct_array(ctx, 8, int);
      |                  ^~~~~~~~~~~~~~~~~~~~~~
      |                  fz_malloc_struct
incdvi.c:48:49: error: expected expression before ‘int’
   48 |       d->pages = fz_malloc_struct_array(ctx, 8, int);
      |                                                 ^~~
incdvi.c:53:65: error: expected expression before ‘int’
   53 |       int *pages = fz_malloc_struct_array(ctx, d->page_cap * 2, int);
      |                                                                 ^~~
incdvi.c: In function ‘incdvi_update’:
incdvi.c:94:16: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
   94 |   int len = buf->len;
      |                ^~
make[1]: *** [Makefile:34：../build/objects/incdvi.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/renderer.o -Idvi/ renderer.c
renderer.c: In function ‘render_rect’:
renderer.c:341:13: warning: implicit declaration of function ‘fz_irect_width’ [-Wimplicit-function-declaration]
  341 |     pitch = fz_irect_width(r) * 3;
      |             ^~~~~~~~~~~~~~
renderer.c:342:72: warning: implicit declaration of function ‘fz_irect_height’; did you mean ‘fz_glyph_height’? [-Wimplicit-function-declaration]
  342 | p *pm = fz_new_pixmap_with_data(ctx, csp, fz_irect_width(r), fz_irect_height(r), NULL, 0, pitch, pixels);
      |                                                              ^~~~~~~~~~~~~~~
      |                                                              fz_glyph_height
renderer.c: In function ‘update_texture’:
renderer.c:596:29: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  596 |       else if (self->scratch->len < new_pixels * 3)
      |                             ^~
make[1]: *** [Makefile:34：../build/objects/renderer.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/engine_tex.o -Idvi/ engine_tex.c
engine_tex.c: In function ‘answer_query’:
engine_tex.c:617:29: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  617 |       if (q->read.pos > data->len)
      |                             ^~
make[1]: *** [Makefile:34：../build/objects/engine_tex.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/synctex.o -Idvi/ synctex.c
synctex.c: In function ‘synctex_update’:
synctex.c:317:32: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  317 |   int cur = stx->cur, len = buf->len;
      |                                ^~
make[1]: *** [Makefile:34：../build/objects/synctex.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/editor.o -Idvi/ editor.c
editor.c: In function ‘editor_append’:
editor.c:338:39: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  338 |   const char *data = (const char *)buf->data;
      |                                       ^~
make[1]: *** [Makefile:34：../build/objects/editor.o] 错误 1
make -C dvi
make[2]: 进入目录“/home/paren/texpresso/src/dvi”
re2c dvi_special.c -o ../../build/objects/dvi_special.re2c.c --tags --bit-vectors
dvi_special.c:44:0: error: unrecognized configuration 'api:style'
make[2]: *** [Makefile:21：../../build/objects/dvi_special.re2c.c] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../../build/objects/dvi_fonttable.o dvi_fonttable.c
dvi_fonttable.c: In function ‘dvi_fonttable_get’:
dvi_fonttable.c:62:27: warning: implicit declaration of function ‘fz_malloc_struct_array’; did you mean ‘fz_malloc_struct’? [-Wimplicit-function-declaration]
   62 |     dvi_fontdef *buffer = fz_malloc_struct_array(ctx, capacity, dvi_fontdef);
      |                           ^~~~~~~~~~~~~~~~~~~~~~
      |                           fz_malloc_struct
dvi_fonttable.c:62:65: error: expected expression before ‘dvi_fontdef’
   62 |     dvi_fontdef *buffer = fz_malloc_struct_array(ctx, capacity, dvi_fontdef);
      |                                                                 ^~~~~~~~~~~
make[2]: *** [Makefile:24：../../build/objects/dvi_fonttable.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -I/usr/include/freetype2 -I/usr/include/libpng16 -c -o ../../build/objects/dvi_resmanager.o dvi_resmanager.c
dvi_resmanager.c: In function ‘tectonic_hooks_open_file’:
dvi_resmanager.c:172:29: warning: implicit declaration of function ‘fz_open_file_ptr_no_close’ [-Wimplicit-function-declaration]
  172 |         fz_stream *stream = fz_open_file_ptr_no_close(ctx, f);
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
dvi_resmanager.c:172:29: warning: initialization of ‘fz_stream *’ {aka ‘struct fz_stream_s *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
dvi_resmanager.c: In function ‘bundle_serve_hooks_cat’:
dvi_resmanager.c:272:9: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
  272 |   buffer->len = size;
      |         ^~
dvi_resmanager.c:273:39: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  273 |   fprintf(stderr, "success:%d size:%lld\n", success, size);
      |                                    ~~~^              ~~~~
      |                                       |              |
      |                                       long long int  uint64_t {aka long unsigned int}
      |                                    %ld
make[2]: *** [Makefile:18：../../build/objects/dvi_resmanager.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../../build/objects/tex_fontmap.o tex_fontmap.c
tex_fontmap.c: In function ‘tex_fontmap_load’:
tex_fontmap.c:83:31: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
   83 |     char *ptr = (char *)buffer->data;
      |                               ^~
tex_fontmap.c:161:22: warning: implicit declaration of function ‘fz_malloc_struct_array’; did you mean ‘fz_malloc_struct’? [-Wimplicit-function-declaration]
  161 |           rawtable = fz_malloc_struct_array(ctx, 128, tex_fontmap_entry);
      |                      ^~~~~~~~~~~~~~~~~~~~~~
      |                      fz_malloc_struct
tex_fontmap.c:161:55: error: expected expression before ‘tex_fontmap_entry’
  161 |           rawtable = fz_malloc_struct_array(ctx, 128, tex_fontmap_entry);
      |                                                       ^~~~~~~~~~~~~~~~~
tex_fontmap.c:166:78: error: expected expression before ‘tex_fontmap_entry’
  166 | ntmap_entry *tmp = fz_malloc_struct_array(ctx, capacity * 2, tex_fontmap_entry);
      |                                                              ^~~~~~~~~~~~~~~~~

tex_fontmap.c:215:45: error: expected expression before ‘tex_fontmap_entry’
  215 |       fz_malloc_struct_array(ctx, capacity, tex_fontmap_entry);
      |                                             ^~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:24：../../build/objects/tex_fontmap.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../../build/objects/tex_vf.o tex_vf.c
tex_vf.c: In function ‘tex_vf_at’:
tex_vf.c:60:26: warning: implicit declaration of function ‘fz_malloc_struct_array’; did you mean ‘fz_malloc_struct’? [-Wimplicit-function-declaration]
   60 |     tex_vf_char *chars = fz_malloc_struct_array(ctx, capacity, tex_vf_char);
      |                          ^~~~~~~~~~~~~~~~~~~~~~
      |                          fz_malloc_struct
tex_vf.c:60:64: error: expected expression before ‘tex_vf_char’
   60 |     tex_vf_char *chars = fz_malloc_struct_array(ctx, capacity, tex_vf_char);
      |                                                                ^~~~~~~~~~~
tex_vf.c: In function ‘tex_vf_load’:
tex_vf.c:85:15: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
   85 |     if (buffer->len < 16) FAIL("file is too small");
      |               ^~
make[2]: *** [Makefile:24：../../build/objects/tex_vf.o] 错误 1
gcc -O2 -ggdb -I. -fPIC -c -o ../../build/objects/tex_enc.o tex_enc.c
tex_enc.c: In function ‘tex_enc_load’:
tex_enc.c:43:41: error: dereferencing pointer to incomplete type ‘fz_buffer’ {aka ‘struct fz_buffer_s’}
   43 |     fz_resize_buffer(ctx, buffer, buffer->len + 1);
      |                                         ^~
make[2]: *** [Makefile:24：../../build/objects/tex_enc.o] 错误 1
re2c pdf_lexer.c -o ../../build/objects/pdf_lexer.re2c.c --tags --bit-vectors
pdf_lexer.c:37:0: error: unrecognized configuration 'api:style'
make[2]: *** [Makefile:21：../../build/objects/pdf_lexer.re2c.c] 错误 1
make[2]: 由于错误目标“all”并未重新制作。
make[2]: 离开目录“/home/paren/texpresso/src/dvi”
make[1]: *** [Makefile:37：../build/objects/libmydvi.a] 错误 2
make[1]: 由于错误目标“texpresso”并未重新制作。
make[1]: 离开目录“/home/paren/texpresso/src”
make: *** [Makefile:8：texpresso] 错误 2

**Comment by let-def** [comment]
I pushed a potential fix but I have not tested it on Ubuntu 20.04.

**Comment by Paren7** [comment]
thanks to your reply, I try it again, but still have something wrong, so I change a Ubuntu 22.04 to build it, but i still get 
paren@paren:~/texpresso$ sudo make texpresso
make -C src texpresso
make[1]: 进入目录“/home/paren/texpresso/src”
g++ -O2 -ggdb -I. -fPIC -o ../build/texpresso ../build/objects/driver.o ../build/objects/main.o ../build/objects/logo.o ../build/objects/sprotocol.o ../build/objects/state.o ../build/objects/fs.o ../build/objects/incdvi.o ../build/objects/myabort.o ../build/objects/renderer.o ../build/objects/engine_tex.o ../build/objects/engine_pdf.o ../build/objects/engine_dvi.o ../build/objects/synctex.o ../build/objects/prot_parser.o ../build/objects/sexp_parser.o ../build/objects/json_parser.o ../build/objects/editor.o ../build/objects/libmydvi.a -lmupdf -lm  -lmupdf-third -lmujs -lz -ljpeg -ljbig2dec -lharfbuzz -lfreetype -lopenjp2 -lgumbo -lSDL2
/usr/bin/ld: 找不到 -lharfbuzz: 没有那个文件或目录
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:13：../build/texpresso] 错误 1
make[1]: 离开目录“/home/paren/texpresso/src”
make: *** [Makefile:8：texpresso] 错误 2

**Comment by let-def** [comment]
What if you just remove `-lharfbuzz` from `LIBS=...` in Makefile.config?

**Comment by Paren7** [comment]
Ok, I install libharfbuzz-dev and I success build it. Thank you

**Comment by let-def** [comment]
I should document that thanks!

**Comment by Paren7** [comment]
Sorry, When I run a test
[info] working directory: /home/paren/texpresso
[info] executable path: /home/paren/texpresso/build/texpresso
[info] document path: /home/paren/texpresso/test
[info] document name: simple.tex
texpresso logo: 512x512
[info] tectonic path: texpresso-tonic
[dvi] loading pdftex.map
bundle_serve_hooks_cat: cannot read answer
[dvi] loading kanjix.map
bundle_serve_hooks_cat: cannot read answer
[dvi] loading ckx.map
bundle_serve_hooks_cat: cannot read answer
[process] launched pid 19999 (using texpresso-tonic)
Aborting from engine_tex.c:207
backtrace() returned 7 addresses
build/texpresso(+0x46046) [0x59aaca30d046]
build/texpresso(+0x4bd55) [0x59aaca312d55]
build/texpresso(+0x409c2) [0x59aaca3079c2]
build/texpresso(main+0x518) [0x59aaca306978]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7dbe9fa29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7dbe9fa29e40]
build/texpresso(+0x3fb15) [0x59aaca306b15]
已中止 (核心已转储)

**Comment by let-def** [comment]
I pushed a few more fixes and the build worked on Ubuntu 20.04.
Please checkout the latest version, but do a clean build (`make distclean` first).

**Comment by Paren7** [comment]
I download the fix and make distclean to rebuild texpresso,
After that,  When I do the simple.tex by texpresso, I can't load it successfully,
I found that there are something need to be download and failed
![image](https://github.com/let-def/texpresso/assets/117136077/c3af78eb-e8c2-4b74-9b68-3795babc0139)

**Comment by let-def** [comment]
There is no reason to use `sudo` when launching texpresso.
And unless you put `http_proxy` in the `env_keep` of `sudoers`, it's not going to be visible from sudo'ed programs.

**Comment by Paren7** [comment]
yes, I used http_proxy

**Comment by let-def** [comment]
And what happens without `sudo`?

**Comment by Paren7** [comment]
![image](https://github.com/let-def/texpresso/assets/117136077/b807be1e-3e63-4cf5-8d89-4fec5551e4c7)
I try to remove sudo ,

**Comment by let-def** [comment]
I think that the submodule was not updated.
Try `git pull && git submodule update --recursive && make`.

If it still not working, try again from a fresh clone:

```
git clone https://github.com/let-def/texpresso
cd texpresso
git submodule update --init --recursive
make -j $(nproc)
build/texpresso test/simple.tex
```

**Comment by let-def** [comment]
I will close the issue for now, assuming that a clean build worked. Feel free to comment if you still have the problem, the issue can be re-opened.
